<!DOCTYPE html>
<html>
<head>
    <style>
        table {
            border: 2px solid black;
            text-align: center;
            border-collapse: collapse;
        }
        th {
            background-color: lightseagreen;
            font-weight: bold;
        }
        th, td {
            border-bottom: 1px solid black;
        }
        tr:nth-child(even) {background-color: #f2f2f2;}
    </style>
</head>
<body>

    <h1>JavaScript Errors - Throw and Try to Catch</h1>

    <p>The <b>try</b> statement lets you test a block of code for errors.</p>
    <p>The <b>catch</b> statement lets you handle the error.</p>
    <p>The <b>throw</b> statement lets you create custom errors.</p>
    <p>The <b>finally</b> statement lets you execute code, after try and catch, regardless of the result.</p>

    <h2>Errors Will Happen!</h2>

    <p>When executing JavaScript code, different errors can occur.</p>

    <p>Errors can be coding errors made by the programmer, errors due to wrong input, and other unforeseeable things.</p>

    <p>This example demonstrates how to use <b>catch</b> to diplay an error.</p>

    <p id="demo"></p>

    <script>
        try {
        adddlert("Welcome guest!");
        }
        catch(err) {
        document.getElementById("demo").innerHTML = err.message;
        }
    </script>

    <p style="background-color: yellow; width: 500px;">JavaScript catches adddlert as an error, and executes the catch code to handle it.</p>

    <h2>JavaScript try and catch</h2>

    <p>The try statement allows you to define a block of code to be tested for errors while it is being executed.</p>
    <p>The catch statement allows you to define a block of code to be executed, if an error occurs in the try block.</p>
    <p>The JavaScript statements try and catch come in pairs.</p>

    <pre style="font-family: courier;">try {
        Block of code to try
    }
    catch(err) {
        Block of code to handle errors
    }</pre>

    <h2>JavaScript Throws Errors</h2>

    <p>When an error occurs, JavaScript will normally stop and generate an error message.</p>
    <p>The technical term for this is: JavaScript will throw an exception (throw an error).</p>

    <p style="background-color: yellow; width: 500px;">JavaScript will actually create an Error object with two properties: name and message.</p>

    <h2>The throw Statement</h2>

    <p>The throw statement allows you to create a custom error.</p>
    <p>Technically you can <strong>throw an exception (throw an error)</strong>.</p>
    <p>The exception can be a JavaScript String, a Number, a Boolean or an Object.</p>

    <p style="font-family: courier;">throw "Too big"; // throw a text<br>
    throw 500; // throw a number</p>

    <p>If you use throw together with try and catch, you can control program flow and generate custom error messages.</p>

    <h2>Input Validation Example</h2>

    <p>This example examines input. If the value is wrong, an exception (err) is thrown.</p>

    <p>The exception (err) is caught by the catch statement and a custom error message is displayed:</p>

    <p>Please input a number between 5 and 10:</p>

    <input id="demo2" type="text">
    <button type="button" onclick="myFunction()">Test Input</button>
    <p id="p01"></p>

    <script>
        function myFunction() {
        var message, x;
        message = document.getElementById("p01");
        message.innerHTML = "";
        x = document.getElementById("demo2").value;
        try { 
            if(x == "")  throw "empty";
            if(isNaN(x)) throw "not a number";
            x = Number(x);
            if(x < 5)  throw "too low";
            if(x > 10)   throw "too high";
        }
        catch(err) {
            message.innerHTML = "Input is " + err;
        }
        }
    </script>

    <h2>HTML Validation</h2>

    <p>The code above is just an example.</p>
    <p>Modern browsers will often use a combination of JavaScript and built-in HTML validation, using predefined validation rules defined in HTML attributes:</p>
    <p style="font-family: courier;"><input id="demo" type="number" min="5" max="10" step="1"></p>

    <h2>The finally Statement</h2>

    <p>The finally statement lets you execute code, after try and catch, regardless of the result:</p>

    <pre style="font-family: courier;">
    try {
        Block of code to try
        }
        catch(err) {
        Block of code to handle errors
        }
        finally {
        Block of code to be executed regardless of the try / catch result
        }
    </pre>

    <p>Please input a number between 5 and 10:</p>

    <input id="demo3" type="text">
    <button type="button" onclick="myFunction2()">Test Input</button>

    <p id="p02"></p>

    <script>
        function myFunction2() {
        var message, x;
        message = document.getElementById("p02");
        message.innerHTML = "";
        x = document.getElementById("demo3").value;
        try { 
            if(x == "")  throw "is empty";
            if(isNaN(x)) throw "is not a number";
            x = Number(x);
            if(x > 10)   throw "is too high";
            if(x < 5)  throw "is too low";
        }
        catch(err) {
            message.innerHTML = "Input " + err;
        }
        finally {
            document.getElementById("demo3").value = "";
        }
        }
    </script>

    <h2>The Error Object</h2>

    <p>JavaScript has a built in error object that provides error information when an error occurs.</p>
    <p>The error object provides two useful properties: name and message.</p>

    <h2>Error Object Properties</h2>

    <table>
        <tr>
            <th>Property</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>name</td>
            <td>Sets or returns an error name</td>
        </tr>
        <tr>
            <td>message</td>
            <td>Sets or returns an error message (a string)</td>
        </tr>
    </table>

    <h2>Error Name Values</h2>

    <p>Six different values can be returned by the error name property:</p>

    <table>
        <tr>
            <th>Error Name</th>
            <th>Description</th>
        </tr>
        <tr>
            <td>EvalError</td>
            <td>An error has occurred in the eval() function</td>
        </tr>
        <tr>
            <td>RangeError</td>
            <td>A number "out of range" has occurred</td>
        </tr>
        <tr>
            <td>ReferenceError</td>
            <td>An illegal reference has occurred</td>
        </tr>
        <tr>
            <td>SyntaxError</td>
            <td>A syntax error has occurred</td>
        </tr>
        <tr>
            <td>TypeError</td>
            <td>A type error has occurred</td>
        </tr>
        <tr>
            <td>URIError</td>
            <td>An error in encodeURI() has occurred</td>
        </tr>
    </table>

    <h3>Eval Error</h3>

    <p>An EvalError indicates an error in the eval() function.</p>
    <p style="background-color: pink; width: 500px">Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead.</p>

    <h3>Range Error</h3>

    <p>A RangeError is thrown if you use a number that is outside the range of legal values.</p>
    <p>For example: You cannot set the number of significant digits of a number to 500.</p>

    <p id="demo4">

    <script>
        var num = 1;
        try {
            num.toPrecision(500);
        }
        catch(err) {
            document.getElementById("demo4").innerHTML = err.name;
        }
    </script>

    <h3>Reference Error</h3>

    <p>A ReferenceError is thrown if you use (reference) a variable that has not been declared:</p>

    <p id="demo4"></p>

    <script>
        var x;
        try {
        x = y + 1;
        }
        catch(err) {
        document.getElementById("demo4").innerHTML = err.name;
        }
    </script>

    <h3>Syntax Error</h3>

    <p>A SyntaxError is thrown if you try to evaluate code with a syntax error.</p>

    <p id="demo5"></p>

    <script>
        try {
        eval("alert('Hello)");
        }
        catch(err) {
        document.getElementById("demo5").innerHTML = err.name;
        }
    </script>

    <h3>Type Error</h3>

    <p>A TypeError is thrown if you use a value that is outside the range of expected types:</p>

    <p id="demo6"></p>

    <script>
        var num = 1;
        try {
        num.toUpperCase();
        }
        catch(err) {
        document.getElementById("demo6").innerHTML = err.name;
        }
    </script>

    <h3>URI (Uniform Resource Identifier) Error</h3>

    <p>A URIError is thrown if you use illegal characters in a URI function:</p>
    <p>Some characters cannot be decoded with decodeURI():</p>

    <p id="demo7"></p>

    <script>
        try {
        decodeURI("%%%");
        }
        catch(err) {
        document.getElementById("demo7").innerHTML = err.name;
        }
    </script>

    <h2>Non-Standard Error Object Properties</h2>

    <p style="background-color: pink; width: 500px;">
    Mozilla and Microsoft defines some non-standard error object properties:
    <br><br>fileName (Mozilla)<br>
    lineNumber (Mozilla)<br>
    columnNumber (Mozilla)<br>
    stack (Mozilla)<br>
    description (Microsoft)<br>
    number (Microsoft)

    <br><br>Do not use these properties in public web sites. They will not work in all browsers.
    </p>







</body>
</html>